// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dghrfpexhbqqotkjbdxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnaHJmcGV4aGJxcW90a2piZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzQwNTMsImV4cCI6MjA2NjM1MDA1M30.a7oANo4xjMOR2doEw56YnZOR6K4ti8b0cFhwwZRvA0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);